@ROOT@/logs/asan* {
    rotate 10
    size 3000M
    olddir old/asan
    missingok
    copytruncate
}

@ROOT@/logs/error* {
    rotate 10
    size 100M
    olddir old/error
    missingok
    copytruncate
    delaycompress
}

@ROOT@/logs/testCases* {
    rotate 10
    size 100M
    olddir old/testCases
    missingok
}

@ROOT@/logs/build* {
    rotate 10
    size 500M
    olddir old/build
    missingok
    delaycompress
}
